#!/usr/bin/env bash

./node_modules/.bin/nodezip -c lambda.zip \
       node_modules \
       lambda-ocr.js \
       lambda-web-api.js \
       config.json \
       signedRequest.js \
       ocr.js \
       client_secret.json \
       drive_token.json

aws --profile bekkops \
    lambda update-function-code \
    --function-name comicsearcher-ocr \
    --zip-file fileb://lambda.zip

aws --profile bekkops \
    lambda update-function-code \
    --function-name comicsearcher-web-api \
    --zip-file fileb://lambda.zip

rm lambda.zip
